get http://localhost:3000/places


### 즐겨찾기 추가
POST http://localhost:3000/users/places
Content-Type: application/json

{
  "place": {
      "id": "r3",
      "title": "부산 광안리 해산물집",
      "image": {
        "src": "busan-seafood.jpg",
        "alt": "광안대교가 보이는 해산물 요리."
      },
      "lat": 35.1533,
      "lon": 129.118,
      "description": "광안리 바다를 바라보며 신선한 해산물을 맛볼 수 있는 맛집."
    }
}

### 즐겨찾기 목록 불러오기
get http://localhost:3000/users/places


### 즟겨찾기 삭제
DELETE http://localhost:3000/users/places/r4